device: "cuda"
dataset: "cifar10"  # Options: cifar10, cifar100, imagenet_val
classifier:
  name: "auto"  # The classifier will be selected automatically based on the dataset
attacks:
  - mode: "SSAH"
    num_iteration: 10
    learning_rate: 0.01
    m: 1
    alpha: 0.5
    lambda_lf: 0.1
    wave: "wavelet"
    Targeted: False  # Add this line to make the attack configurable
  - mode: "DeepFool"
    steps: 50
    overshoot: 0.02
    learning_rate: 0.005
  - mode: "PGD"
    eps: 8/255
    alpha: 2/225
    steps: 10
    random_start: True
  - mode: "CW"
    c: 1
    kappa: 0
    steps: 100
    lr: 0.01
  - mode: "JSMA"
    theta: 1.0
    gamma: 0.1
